MyAppointer/Models/Appointments.cs
//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MyAppointer.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Appointments
    {
        public int Id { get; set; }
        public int BookDate { get; set; }
        public int StartTime { get; set; }
        public int EndTime { get; set; }
        public int JobOwnerId { get; set; }
        public Nullable<int> UserId { get; set; }
        public bool isReserved { get; set; }
        public string Description { get; set; }
    
        public virtual JobOwners JobOwners { get; set; }
        public virtual Users Users { get; set; }
    }
}

MyAppointer/Models/Users.cs
//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MyAppointer.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    using System.Web.Mvc; 
    
    public partial class Users
    {
        public Users()
        {
            this.Appointments = new HashSet<Appointments>();
            this.JobOwners = new HashSet<JobOwners>();
            this.Jobs = new HashSet<Jobs>();
        }
    
        public int Id { get; set; }
        [Required]
        [EmailAddress]
        [StringLength(32)]
        [DataType(DataType.EmailAddress)]
        [Remote("doesUserNameExist", "User", HttpMethod = "POST", ErrorMessage = "User name already exists. Please enter a different user name.")]
        public string Email { get; set; }

        [Required]
        [DataType(DataType.Password)]
        [StringLength(64, MinimumLength = 6)]
        public string Password { get; set; }

        [DataType(DataType.PhoneNumber)]
        [Display(Name = "Mobile")]
        [Required]
        [StringLength(11)]
        [Remote("doesPhoneNumberExist", "User", HttpMethod = "POST", ErrorMessage = "Phone Number already exists. Please enter a different phne number.")]
        //^[01]?[- .]?(\([2-9]\d{2}\)|[2-9]\d{2})[- .]?\d{3}[- .]?\d{4}$
        [RegularExpression(@"^09(1[0-9]|3[1-9]|2[1-9])-?[0-9]{7}$", ErrorMessage = "Enter Your Mobile Phone Number like this: 09127404062")]
        public string Phone { get; set; }

        [Required]
        [Display(Name = "Your First Name and Last Name")]
        public string FullName { get; set; }
        public string About { get; set; }
        public string City { get; set; }
        public string Role { get; set; }
    
        public virtual ICollection<Appointments> Appointments { get; set; }
        public virtual ICollection<JobOwners> JobOwners { get; set; }
        public virtual ICollection<Jobs> Jobs { get; set; }
    }
}

MyAppointer/Controllers/AppointmentController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Data.Entity.Infrastructure;
using System.Linq;
using System.Net;
using System.Net.Http;
using System.Web;
using System.Web.Http;
using MyAppointer.Models;
using Newtonsoft.Json;

namespace MyAppointer.Controllers
{
    public class AppointmentController : ApiController
    {
        private MyAppointerEntities db = new MyAppointerEntities();

        // GET api/Appointment
        public string GetAppointmentsOfDay(int BookDate,int JobOwnerId)
        {
            var appointments = db.Appointments.Where(a => a.BookDate.Equals(BookDate) && a.JobOwnerId.Equals(JobOwnerId));
            var query = from appointment in appointments
                        select new
                        {
                            startTime = appointment.StartTime,
                            endTime = appointment.EndTime
                        };

            var json = JsonConvert.SerializeObject(query.ToArray()); 

            return json;
        }

        // GET api/Appointment
        public IEnumerable<Appointments> GetAppointments()
        {
            var appointments = db.Appointments.Include(a => a.JobOwners).Include(a => a.Users);
            return appointments.AsEnumerable();
        }

        // GET api/Appointment/5
        public Appointments GetAppointments(int id)
        {
            Appointments appointments = db.Appointments.Find(id);
            if (appointments == null)
            {
                throw new HttpResponseException(Request.CreateResponse(HttpStatusCode.NotFound));
            }

            return appointments;
        }

        // PUT api/Appointment/5
        public HttpResponseMessage PutAppointments(int id, Appointments appointments)
        {
            if (!ModelState.IsValid)
            {
                return Request.CreateErrorResponse(HttpStatusCode.BadRequest, ModelState);
            }

            if (id != appointments.Id)
            {
                return Request.CreateResponse(HttpStatusCode.BadRequest);
            }

            db.Entry(appointments).State = EntityState.Modified;

            try
            {
                db.SaveChanges();
            }
            catch (DbUpdateConcurrencyException ex)
            {
                return Request.CreateErrorResponse(HttpStatusCode.NotFound, ex);
            }

            return Request.CreateResponse(HttpStatusCode.OK);
        }

        // POST api/Appointment
        public HttpResponseMessage PostAppointments(Appointments appointments)
        {
            int overlap_flag = 0;
            HttpResponseMessage response = new HttpResponseMessage();

            if (ModelState.IsValid)
            {
                foreach(Appointments appointment in db.Appointments)
                {
                    if (appointment.BookDate == appointments.BookDate) {
                        if ((appointment.StartTime <= appointments.StartTime) && (appointment.EndTime >= appointments.StartTime)) {
                            overlap_flag = 1;
                            break;
                        }else if ((appointment.EndTime >= appointments.EndTime) && (appointment.StartTime <= appointments.EndTime))
                        {
                            overlap_flag = 1;
                            break;
                        }
                    } 
                }

                if (overlap_flag == 1)
                {
                    response = Request.CreateResponse(HttpStatusCode.OK, "overlap");
                    response.Headers.Location = new Uri(Url.Link("DefaultApi", new { id = appointments.Id }));
                }
                else
                {
                    db.Appointments.Add(appointments);
                    db.SaveChanges();

                    response = Request.CreateResponse(HttpStatusCode.Created, appointments);
                    response.Headers.Location = new Uri(Url.Link("DefaultApi", new { id = appointments.Id }));
                }

                return response;
            }
            else
            {
                return Request.CreateErrorResponse(HttpStatusCode.BadRequest, ModelState);
            }
        }

        // DELETE api/Appointment/5
        public HttpResponseMessage DeleteAppointments(int id)
        {
            Appointments appointments = db.Appointments.Find(id);
            if (appointments == null)
            {
                return Request.CreateResponse(HttpStatusCode.NotFound);
            }

            db.Appointments.Remove(appointments);

            try
            {
                db.SaveChanges();
            }
            catch (DbUpdateConcurrencyException ex)
            {
                return Request.CreateErrorResponse(HttpStatusCode.NotFound, ex);
            }

            return Request.CreateResponse(HttpStatusCode.OK, appointments);
        }

        protected override void Dispose(bool disposing)
        {
            db.Dispose();
            base.Dispose(disposing);
        }
    }
}

MyAppointer/Controllers/UserController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using System.Transactions;
using System.Web.Security;
using DotNetOpenAuth.AspNet;
using Microsoft.Web.WebPages.OAuth;
using WebMatrix.WebData;
using MyAppointer.Models;
using System.Security.Cryptography;

namespace MyAppointer.Controllers
{
    public class UserController : Controller
    {
        private MyAppointerEntities db = new MyAppointerEntities();

        public ActionResult Index()
        {
            if (Session["Role"] != null)
            {
                if (Session["Role"].ToString() == "admin")
                {
                    return View(db.Users.ToList());
                }
                else if (Session["Role"].ToString() == "jobowner" || (Session["Role"].ToString() == "user"))
                {
                    return RedirectToAction("ListAppointment");
                }
            }
            return RedirectToAction("Login");
        }

        public ActionResult Details(int id = 0)
        {
           
            if (Session["Role"] == null)
            {
                return RedirectToAction("Login");
            }
            else if (Session["Role"].ToString() == "jobowner" || (Session["Role"].ToString() == "user"))
            {
                id = Int32.Parse(Session["LogedUserID"].ToString());
            }

            Users users = db.Users.Find(id);
            if (users == null)
            {
                return HttpNotFound();
            }
            return View(users);
        }



        public ActionResult Create()
        {
            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(Users users)
        {

            if (ModelState.IsValid)
            {
                db.Users.Add(users);
                db.SaveChanges();
                if (users.Role == "jobowner")
                {
                    Session["LogedUserID"] = users.Id.ToString();
                    Session["LogedUserFullname"] = users.FullName;
                    Session["Role"] = users.Role;
                    return RedirectToAction("Create", "Job", new { FirstJobOwner = users.Id });
                }
                else
                {
                    return RedirectToAction("Index", "Home");
                }
            }
            return View(users);
        }

        [HttpPost]
        public JsonResult doesUserNameExist(Users u)
        {
            var v = db.Users.Where(model => model.Email.Equals(u.Email)).FirstOrDefault();
            return Json(v == null);
        }

        [HttpPost]
        public JsonResult doesPhoneNumberExist(Users u)
        {
            var v = db.Users.Where(model => model.Phone.Equals(u.Phone)).FirstOrDefault();
            return Json(v == null);

        }

        //login
        [HttpGet]
        public ActionResult Login()
        {
            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Login(Users l)
        {

            using (db)
            {
                var v = db.Users.Where(model => model.Email.Equals(l.Email) && model.Password.Equals(l.Password)).FirstOrDefault();
                if (v != null)
                {
                    Session["LogedUserID"] = v.Id.ToString();
                    Session["LogedUserFullname"] = v.FullName;
                    Session["Role"] = v.Role;

                    HttpCookie aCookie = new HttpCookie("userInfo");
                    aCookie.Values["userName"] = l.Email;
                    aCookie.Values["Role"] = l.Role;
                    aCookie.Values["lastVisit"] = DateTime.Now.ToString();
                    aCookie.Expires = DateTime.Now.AddDays(1);
                    Response.Cookies.Add(aCookie);
                    if(v.Role == "user")
                    {
                        return RedirectToAction("Index", "Home");
                    }
                    else
                    {
                        return RedirectToAction("AfterLogin", "User");
                    }
                }
                else
                {
                    ModelState.AddModelError("", "Email Or Password is Incorrect.");
                }
            }
            return View();
        }
        public ActionResult AfterLogin()
        {
            if (Session["LogedUserID"] != null)
            {
                return View();
            }
            else
            {
                return RedirectToAction("Login");
            }
        }

        //LogOff

        [HttpGet]
        public ActionResult LogOff()
        {
            
            Session["LogedUserID"] = null;
            Session["LogedUserFullname"] = null;
            Session["Role"] = null;
            if (Request.Cookies["UserInfo"]["userName"] != null)
            {
                Request.Cookies["UserInfo"]["userName"] = null;
            }
            return RedirectToAction("Index", "Home");//sths
        }

        //
        // GET: /User/Edit/5

        [HttpGet]
        public ActionResult Edit(int? id)
        {
            if (Session["Role"] != null)
            {
                if (Session["Role"].ToString() == null)
                {
                    return RedirectToAction("Login");
                }
                else if (Session["Role"].ToString() == "jobowner" || (Session["Role"].ToString() == "user"))
                {
                    id = Int32.Parse(Session["LogedUserID"].ToString());
                }

                Users user = db.Users.Find(id);
                if (user == null)
                {
                    return HttpNotFound();
                }
                ViewBag.Email = user.Email;
                ViewBag.Phone = user.Phone;
                return View(user);
            }
            return RedirectToAction("Login");
        }

        // POST: /User/Edit/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(Users editu ,string NewEmail,string NewPhone)
        {
            editu.Email = NewEmail;
            editu.Phone = NewPhone;
            if (ModelState.IsValid)
            {
                db.Entry(editu).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("AfterLogin", "User");
            }
            return View(editu);
        }

        //
        // GET: /User/Delete/5

        public ActionResult Delete(int id = 0)
        {
            if (Session["Role"] == null)
            {
                return RedirectToAction("Login");
            }
            else if (Session["Role"].ToString() == "jobowner" || (Session["Role"].ToString() == "user"))
            {
                id = Int32.Parse(Session["LogedUserID"].ToString());
            }

            Users users = db.Users.Find(id);
            if (users == null)
            {
                return HttpNotFound();
            }
            return View(users);
        }

        //
        // POST: /User/Delete/5

        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            Users users = db.Users.Find(id);
            db.Users.Remove(users);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        public ActionResult ListAppointment()
        {
            IEnumerable<MyAppointer.Models.Appointments> appointments;
            if (Session["Role"] == null)
            {
                return RedirectToAction("Login");
            }
            else if (Session["Role"].ToString() == "jobowner") {
                var str = Session["LogedUserID"].ToString();
                appointments = db.Appointments.Where(model => model.JobOwners.UserId.Equals(Int32.Parse(str)));
            }
            else if(Session["Role"].ToString() == "user")
            {
                int id = Int32.Parse(Session["LogedUserID"].ToString());
                appointments = db.Appointments.Where(model => model.JobOwnerId.Equals(id));
            }
            else
            {
                appointments = db.Appointments;
            }
            return View(appointments);
        }



        protected override void Dispose(bool disposing)
        {
            db.Dispose();
            base.Dispose(disposing);
        }
        
    }
}

MyAppointer/Views/User/AfterLogin.cshtml
@{
    Layout = "~/Views/Shared/Personal.cshtml";
}
@model MyAppointer.Models.Users

@{
    ViewBag.Title = "AfterLogin";
}

@if (Session["LogedUserFullname"] != null)
{
    <text>
        <h1>Time tabel of job owner</h1>
    </text>
}

MyAppointer/Views/User/Appointments.cshtml
@model IEnumerable<MyAppointer.Models.Appointments>

@{
    ViewBag.Title = "Appointments";
}

<h2>Index</h2>

<table>
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.BookDate )
        </th>
        <th>
            @Html.DisplayNameFor(model => model.JobOwners.Jobs.Title)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.StartTime )
        </th>
        <th>
            @Html.DisplayNameFor(model => model.EndTime )
        </th>
    </tr>

@foreach (var item in Model) {
    <tr>
        <td>
            @Html.DisplayFor(modelItem => item.BookDate)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.JobOwners.Jobs.Title)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.StartTime )
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.EndTime )
        </td>
        <td>
            @Html.ActionLink("Delete","Delete", "Appointment", new { id=item.Id })
        </td>
    </tr>
}

</table>

MyAppointer/Views/User/Create.cshtml
@model MyAppointer.Models.Users

@{
    ViewBag.Title = "Sign Up";
    
}
<div class="container" style="width:1000px;">
    <div class="row">
        <div class="col-sm-6 col-md-4 col-md-offset-4" style="margin-left:200px;">
            <h2 style="margin-left:70px;margin-bottom:20px;font-size:30px;">Sign Up</h2>
@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    @Html.ValidationSummary(true)

    <fieldset>
        <legend>Users</legend>

        <div class="editor-label">
            @Html.LabelFor(model => model.Email)
        </div>
        <div class="editor-field">
            @Html.EditorFor(model => model.Email)
            @Html.ValidationMessageFor(model => model.Email)
        </div>
     
        <div class="editor-label">
            @Html.LabelFor(model => model.Password)
        </div>
        <div class="editor-field">
            @Html.EditorFor(model => model.Password)
            @Html.ValidationMessageFor(model => model.Password)
        </div>

        <div class="editor-label">
            @Html.LabelFor(model => model.Phone)
        </div>
        <div class="editor-field">
            @Html.EditorFor(model => model.Phone)
            @Html.ValidationMessageFor(model => model.Phone)
        </div>

        <div class="editor-label">
            @Html.LabelFor(model => model.FullName)
        </div>
        <div class="editor-field">
            @Html.EditorFor(model => model.FullName)
            @Html.ValidationMessageFor(model => model.FullName)
        </div>

        <div class="editor-label">
            @Html.LabelFor(model => model.City)
        </div>
        <div class="editor-field">
            @Html.EditorFor(model => model.City)
            @Html.ValidationMessageFor(model => model.City)
        </div>

        <div class="editor-label">
            @Html.LabelFor(model => model.About)
        </div>
        <div class="editor-field">
            @Html.EditorFor(model => model.About)
            @Html.ValidationMessageFor(model => model.About)
        </div>

        <div class="editor-label">
            @Html.LabelFor(model => model.Role)
        </div>

        <div class="editor-field">
            User @Html.RadioButtonFor(model => model.Role, "user")
            <br />
            Job Owner @Html.RadioButtonFor(model => model.Role, "jobowner")
            @Html.ValidationMessageFor(model => model.Role)
        </div>

        <p>
            <input type="submit" value="Create" />
        </p>
    </fieldset>
}

        </div>
    </div>
</div>



@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

MyAppointer/Views/User/Delete.cshtml
@model MyAppointer.Models.Users

@{
    ViewBag.Title = "Delete";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<fieldset>
    <legend>Users</legend>

    <div class="display-label">
         @Html.DisplayNameFor(model => model.Email)
    </div>
    <div class="display-field">
        @Html.DisplayFor(model => model.Email)
    </div>

    <div class="display-label">
         @Html.DisplayNameFor(model => model.Password)
    </div>
    <div class="display-field">
        @Html.DisplayFor(model => model.Password)
    </div>

    <div class="display-label">
         @Html.DisplayNameFor(model => model.Phone)
    </div>
    <div class="display-field">
        @Html.DisplayFor(model => model.Phone)
    </div>

    <div class="display-label">
         @Html.DisplayNameFor(model => model.FullName)
    </div>
    <div class="display-field">
        @Html.DisplayFor(model => model.FullName)
    </div>

    <div class="display-label">
         @Html.DisplayNameFor(model => model.About)
    </div>
    <div class="display-field">
        @Html.DisplayFor(model => model.About)
    </div>

    <div class="display-label">
         @Html.DisplayNameFor(model => model.City)
    </div>
    <div class="display-field">
        @Html.DisplayFor(model => model.City)
    </div>

    <div class="display-label">
         @Html.DisplayNameFor(model => model.Role)
    </div>
    <div class="display-field">
        @Html.DisplayFor(model => model.Role)
    </div>
</fieldset>
@using (Html.BeginForm()) {
    @Html.AntiForgeryToken()
    <p>
        <input type="submit" value="Delete" /> |
        @Html.ActionLink("Back to List", "Index")
    </p>
}

MyAppointer/Views/User/Details.cshtml
@model MyAppointer.Models.Users

@{
    ViewBag.Title = "Details";
}

<h2>Details</h2>

<fieldset>
    <legend>Users</legend>

    <div class="display-label">
         @Html.DisplayNameFor(model => model.Email)
    </div>
    <div class="display-field">
        @Html.DisplayFor(model => model.Email)
    </div>

    <div class="display-label">
         @Html.DisplayNameFor(model => model.Password)
    </div>
    <div class="display-field">
        @Html.DisplayFor(model => model.Password)
    </div>

    <div class="display-label">
         @Html.DisplayNameFor(model => model.Phone)
    </div>
    <div class="display-field">
        @Html.DisplayFor(model => model.Phone)
    </div>

    <div class="display-label">
         @Html.DisplayNameFor(model => model.FullName)
    </div>
    <div class="display-field">
        @Html.DisplayFor(model => model.FullName)
    </div>

    <div class="display-label">
         @Html.DisplayNameFor(model => model.About)
    </div>
    <div class="display-field">
        @Html.DisplayFor(model => model.About)
    </div>

    <div class="display-label">
         @Html.DisplayNameFor(model => model.City)
    </div>
    <div class="display-field">
        @Html.DisplayFor(model => model.City)
    </div>

    <div class="display-label">
         @Html.DisplayNameFor(model => model.Role)
    </div>
    <div class="display-field">
        @Html.DisplayFor(model => model.Role)
    </div>
</fieldset>
<p>
    @Html.ActionLink("Edit", "Edit", new { id=Model.Id }) |
    @Html.ActionLink("Back to List", "Index")
</p>

MyAppointer/Views/User/Edit.cshtml
@model MyAppointer.Models.Users
@{
    ViewBag.Title = "My Profile";
}

<h2>Edit My Profile</h2>
<script src="@Url.Content("~/Scripts/jquery.validate.min.js")" type="text/javascript"></script>
<script src="@Url.Content("~/Scripts/jquery.validate.unobtrusive.min.js")" type="text/javascript"></script>

@using (Html.BeginForm()) {
    @Html.AntiForgeryToken()
    @Html.ValidationSummary(true)
    @Html.HiddenFor(model => model.Id)

    <fieldset>
        <legend>User Profile</legend>
        <br />
        <div style="color:Green">@ViewData["Status"]</div>
        <br />
        @Html.HiddenFor(model => model.Id)

        <div class="editor-label">
            @Html.LabelFor(model => model.Email)
        </div>
        <div class="editor-field">
            <input type="text" name="NewEmail" value="@ViewBag.Email"/>
            @Html.HiddenFor(model => model.Email)
            @Html.ValidationMessageFor(model => model.Email)
        </div>

        <div class="editor-label">
            @Html.LabelFor(model => model.Password)
        </div>
        <div class="editor-field">
            @Html.EditorFor(model => model.Password)
            @Html.ValidationMessageFor(model => model.Password)
        </div>

        <div class="editor-label">
            @Html.LabelFor(model => model.Phone)
        </div>
        <div class="editor-field">
            <input type="text" name="NewPhone" value="@ViewBag.Phone" />
            @Html.HiddenFor(model => model.Phone)
            @Html.ValidationMessageFor(model => model.Phone)
        </div>

        <div class="editor-label">
            @Html.LabelFor(model => model.FullName)
        </div>
        <div class="editor-field">
            @Html.EditorFor(model => model.FullName)
            @Html.ValidationMessageFor(model => model.FullName)
        </div>

        <div class="editor-label">
            @Html.LabelFor(model => model.About)
        </div>
        <div class="editor-field">
            @Html.EditorFor(model => model.About)
            @Html.ValidationMessageFor(model => model.About)
        </div>

        <div class="editor-label">
            @Html.LabelFor(model => model.City)
        </div>
        <div class="editor-field">
            @Html.EditorFor(model => model.City)
            @Html.ValidationMessageFor(model => model.City)
        </div>
        <div style="display:none" class="editor-field">
            @Html.EditorFor(model => model.Role)
            @Html.ValidationMessageFor(model => model.Role)
        </div>

        <p>
            <input type="submit" value="Save" />
        </p>
    </fieldset>
}

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

MyAppointer/Views/User/Index.cshtml
@model IEnumerable<MyAppointer.Models.Users>

@{
    ViewBag.Title = "Index";
}

<h2>Index</h2>

<p>
    @Html.ActionLink("Create New", "Create")
</p>
<table>
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.Email)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Password)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Phone)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.FullName)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.About)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.City)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Role)
        </th>
        <th></th>
    </tr>

@foreach (var item in Model) {
    <tr>
        <td>
            @Html.DisplayFor(modelItem => item.Email)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Password)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Phone)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.FullName)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.About)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.City)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Role)
        </td>
        <td>
            @Html.ActionLink("Edit", "Edit", new { id=item.Id }) |
            @Html.ActionLink("Details", "Details", new { id=item.Id }) |
            @Html.ActionLink("Delete", "Delete", new { id=item.Id })
        </td>
    </tr>
}

</table>

MyAppointer/Views/User/ListAppointment.cshtml
@model IEnumerable<MyAppointer.Models.Appointments>

@{
    Layout = null;
}

<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>ListAppointment</title>
</head>
<body>
    <p>
        @Html.ActionLink("Create New", "Create")
    </p>
    <table>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.BookDate)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.StartTime)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.EndTime)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.JobOwnerId)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.UserId)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.isReserved)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Description)
            </th>
            <th></th>
        </tr>
    
    @foreach (var item in Model) {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.BookDate)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.StartTime)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.EndTime)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.JobOwnerId)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.UserId)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.isReserved)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Description)
            </td>
            <td>
                @Html.ActionLink("Edit", "Edit", new { id=item.Id }) |
                @Html.ActionLink("Details", "Details", new { id=item.Id }) |
                @Html.ActionLink("Delete", "Delete", new { id=item.Id })
            </td>
        </tr>
    }
    
    </table>
</body>
</html>