MyAppointer/Models/JobTypes.cs
//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MyAppointer.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class JobTypes
    {
        public JobTypes()
        {
            this.Jobs = new HashSet<Jobs>();
        }
    
        public int Id { get; set; }
        public string Title { get; set; }
    
        public virtual ICollection<Jobs> Jobs { get; set; }
    }
}

MyAppointer/Models/Jobs.cs
//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MyAppointer.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Jobs
    {
        public Jobs()
        {
            this.JobOwners = new HashSet<JobOwners>();
        }
    
        public int Id { get; set; }
        public string Title { get; set; }
        public string JobPhone { get; set; }
        public string About { get; set; }
        public string Address { get; set; }
        public int JobTypeId { get; set; }
        public int FirstJobOwner { get; set; }
    
        public virtual ICollection<JobOwners> JobOwners { get; set; }
        public virtual JobTypes JobTypes { get; set; }
        public virtual Users Users { get; set; }
    }
}

MyAppointer/Controllers/JobController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using MyAppointer.Models;

namespace MyAppointer.Controllers
{
    public class JobController : Controller
    {
        private MyAppointerEntities db = new MyAppointerEntities();

        //
        // GET: /Job/

        public ActionResult Index()
        {
            
            var jobs = db.Jobs.Include(j => j.JobTypes).Include(j => j.Users);
            return View(jobs.ToList());
        }

        //
        // GET: /Job/Details/5

        public ActionResult Details(int id = 0)
        {
            //id = db.JobOwners.Where(model => model.UserId.Equals(id)).FirstOrDefault().Id;

            Jobs jobs = db.Jobs.Where(model => model.Id.Equals(id)).FirstOrDefault() ;
            if (jobs == null)
            {
                return HttpNotFound();
            }
            return View(jobs);
        }
        //get
        [HttpGet]
        public ActionResult Create()
        {
            if (Session["LogedUserID"] == null)
            {
                return RedirectToAction("Login", "User");
            }
            ViewBag.JobTypeId = new SelectList(db.JobTypes, "Id", "Title", "Select Job Type");
            ViewBag.FirstJobOwner = new SelectList(db.Users, "Id", "Email");          

            return View();
        }

        //
        // POST: /Job/Create

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(BigViewModel bv)
        {
            if (Session["LogedUserID"] == null)
            {
                return RedirectToAction("Login", "User");
            }
            else if (Session["LogedUserID"].ToString() == "user")
            {
                return RedirectToAction("Index", "Home");
            }

            bv.Jobs.JobTypes = db.JobTypes.Where(model => model.Id.Equals(bv.Jobs.JobTypeId)).FirstOrDefault();
            
                bv.Jobs.FirstJobOwner = Int32.Parse(Session["LogedUserID"].ToString());
                bv.Jobs.Users = db.Users.Where(model => model.Id.Equals(bv.Jobs.FirstJobOwner)).FirstOrDefault();
                db.Jobs.Add(bv.Jobs);
                db.SaveChanges();

                bv.JobOwners = new JobOwners();
                bv.JobOwners.JobId = bv.Jobs.Id;
                bv.JobOwners.UserId = bv.Jobs.FirstJobOwner;
                db.JobOwners.Add(bv.JobOwners);
                db.SaveChanges();

                WorkingTimes WT = new WorkingTimes();

                WT.JobOwnerId = bv.JobOwners.Id;

                db.WorkingTimes.Add(WT);
                db.SaveChanges();
                
                foreach (WeeklyWorkingDays wwd in bv.WeeklyWorkingDays)
                {
                    wwd.WorkingTimes = WT;
                    db.WeeklyWorkingDays.Add(wwd);
                    db.SaveChanges();

                }

                foreach (WeeklyWorkingTimes wwt in bv.WeeklyWorkingTimes)
                {
                    wwt.WorkingTimes = WT;
                    db.WeeklyWorkingTimes.Add(wwt);
                    db.SaveChanges();

                }

            return RedirectToAction("Index", "Home");
        }

        //
        // GET: /Job/Edit/5

        public ActionResult Edit(int id = 0)
        {
            if (Session["LogedUserID"] == null)
            {
                return RedirectToAction("Login", "User");
            }
            else if (Session["Role"].ToString() == "user")
            {
                return RedirectToAction("Index", "Home");
            }

            Jobs jobs = db.Jobs.Find(id);
            if (jobs == null)
            {
                return HttpNotFound();
            }
            ViewBag.JobTypeId = new SelectList(db.JobTypes, "Id", "Title", jobs.JobTypeId);
            ViewBag.FirstJobOwner = new SelectList(db.Users, "Id", "Email", jobs.FirstJobOwner);
            return View(jobs);
        }

        //
        // POST: /Job/Edit/5

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(Jobs jobs)
        {
            if (Session["LogedUserID"] == null)
            {
                return RedirectToAction("Login", "User");
            }
            else if (Session["LogedUserID"].ToString() == "user")
            {
                return RedirectToAction("Index", "Home");
            }

            if (ModelState.IsValid)
            {
                db.Entry(jobs).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            ViewBag.JobTypeId = new SelectList(db.JobTypes, "Id", "Title", jobs.JobTypeId);
            ViewBag.FirstJobOwner = new SelectList(db.Users, "Id", "Email", jobs.FirstJobOwner);
            return View(jobs);
        }

        //
        // GET: /Job/Delete/5

        public ActionResult Delete(int id = 0)
        {
            if (Session["Role"] == null)
            {
                return RedirectToAction("Login", "User");
            }
            else if (Session["Role"].ToString() == "user")
            {
                return RedirectToAction("Index", "Home");
            }

            Jobs jobs = db.Jobs.Find(id);
            if (jobs == null)
            {
                return HttpNotFound();
            }
            return View(jobs);
        }

        //
        // POST: /Job/Delete/5

        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            if (Session["Role"] == null)
            {
                return RedirectToAction("Login", "User");
            }
            else if (Session["Role"].ToString() == "user")
            {
                return RedirectToAction("Index", "Home");
            }

            Jobs jobs = db.Jobs.Find(id);
            db.Jobs.Remove(jobs);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            db.Dispose();
            base.Dispose(disposing);
        }
    }
}

MyAppointer/Views/Job/Create.cshtml
@model MyAppointer.Models.BigViewModel

@{
    ViewBag.Title = "Creating your Job";
}

@section JavaScript
{
    <script type="text/javascript" src="@Url.Content("~/Scripts/CreateJob.js")"></script>
 
}

<h2>Creating your Job</h2>

@using (Html.BeginForm("Create", "Job", FormMethod.Post))
{
    @Html.AntiForgeryToken()
    @Html.ValidationSummary(true)

    <fieldset>
        <legend>Jobs</legend>

        <div class="editor-label">
            @Html.LabelFor(model => model.Jobs.Title)
        </div>
        <div class="editor-field">
            @Html.EditorFor(model => model.Jobs.Title)
            @Html.ValidationMessageFor(model => model.Jobs.Title)
        </div>

        <div class="editor-label">
            @Html.LabelFor(model => model.Jobs.JobPhone)
        </div>
        <div class="editor-field">
            @Html.EditorFor(model => model.Jobs.JobPhone)
            @Html.ValidationMessageFor(model => model.Jobs.JobPhone)
        </div>

        <div class="editor-label">
            @Html.LabelFor(model => model.Jobs.Address)
        </div>
        <div class="editor-field">
            @Html.EditorFor(model => model.Jobs.Address)
            @Html.ValidationMessageFor(model => model.Jobs.Address)
        </div>
        
        <div class="editor-label">
            @Html.LabelFor(model => model.Jobs.About)
        </div>
        <div class="editor-field">
            @Html.EditorFor(model => model.Jobs.About)
            @Html.ValidationMessageFor(model => model.Jobs.About)
        </div>

        <div class="editor-label">
            @Html.LabelFor(model => model.Jobs.JobTypeId, "Job Types")
        </div>
        <div class="editor-field">
           
        @Html.DropDownList("JobTypeId")

</div>

    <div  class="editor-label">
        @Html.HiddenFor(model => model.Jobs.JobTypeId)
    </div>

        <div class="editor-field days-wrapper">
            @Html.Raw("</br>  Days  </br>")
            @Html.HiddenFor(model => model.WeeklyWorkingDays[0].Id)
            @Html.EditorFor(model => model.WeeklyWorkingDays[0].Day)
        </div>
        <br /><input type="button" id="Add_day" value="Add Day"/><br />

        <div class="editor-field times-wrapper">
            @Html.Raw("</br>  Times  </br>")
            @Html.HiddenFor(model => model.WeeklyWorkingTimes[0].Id)
            @Html.EditorFor(model => model.WeeklyWorkingTimes[0].StartTime)
            @Html.EditorFor(model => model.WeeklyWorkingTimes[0].EndTime)
        </div>
        <br /><input type="button" id="Add_Time" value="Add Time" /><br />

        <p>
            <input type="submit" value="Create" />
        </p>
    </fieldset>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

MyAppointer/Views/Job/Delete.cshtml
@model MyAppointer.Models.Jobs

@{
    ViewBag.Title = "Delete";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<fieldset>
    <legend>Jobs</legend>

    <div class="display-label">
         @Html.DisplayNameFor(model => model.Title)
    </div>
    <div class="display-field">
        @Html.DisplayFor(model => model.Title)
    </div>

    <div class="display-label">
         @Html.DisplayNameFor(model => model.JobPhone)
    </div>
    <div class="display-field">
        @Html.DisplayFor(model => model.JobPhone)
    </div>

    <div class="display-label">
         @Html.DisplayNameFor(model => model.About)
    </div>
    <div class="display-field">
        @Html.DisplayFor(model => model.About)
    </div>

    <div class="display-label">
         @Html.DisplayNameFor(model => model.Address)
    </div>
    <div class="display-field">
        @Html.DisplayFor(model => model.Address)
    </div>

    <div class="display-label">
         @Html.DisplayNameFor(model => model.JobTypes.Title)
    </div>
    <div class="display-field">
        @Html.DisplayFor(model => model.JobTypes.Title)
    </div>

    <div class="display-label">
         @Html.DisplayNameFor(model => model.Users.Email)
    </div>
    <div class="display-field">
        @Html.DisplayFor(model => model.Users.Email)
    </div>
</fieldset>
@using (Html.BeginForm()) {
    @Html.AntiForgeryToken()
    <p>
        <input type="submit" value="Delete" /> |
        @Html.ActionLink("Back to List", "Index")
    </p>
}

MyAppointer/Views/Job/Details.cshtml
@model MyAppointer.Models.Jobs

@{
    ViewBag.Title = "Details";
}

<h2>@Html.DisplayFor(model => model.Title)'s Info</h2>

<fieldset style="font-size:1.4em;">
    @*<legend>Jobs</legend>*@
    <br/>
    <br/>
    <div class="display-label">
         @Html.DisplayNameFor(model => model.Title)
    </div>

    <div class="display-field">
        @Html.DisplayFor(model => model.Title)
    </div>

    <br />


    <div class="display-label">
        @Html.DisplayName("Job Category")
    </div>
    <div class="display-field">
        @Html.DisplayFor(model => model.JobTypes.Title)
    </div>


    <br/>


    <div class="display-label">
        @Html.DisplayName("Name")
    </div>
    <div class="display-field">
        @Html.DisplayFor(model => model.Users.FullName)
    </div>

    <br/>
    <div class="display-label">
         @Html.DisplayName("Phone Number")
    </div>
    <div class="display-field">
        @Html.DisplayFor(model => model.JobPhone)
    </div>



    <br/>

    <div class="display-label">
        @Html.DisplayNameFor(model => model.Address)
    </div>
    <div class="display-field">
        @Html.DisplayFor(model => model.Address)
    </div> 

    <br/>


    <div class="display-label">
        @Html.DisplayNameFor(model => model.Users.Email)
    </div>
    <div class="display-field">
        @Html.DisplayFor(model => model.Users.Email)
    </div>

    <br/>

    <div class="display-label">
         @Html.DisplayNameFor(model => model.About)
    </div>
    <div class="display-field">
        @Html.DisplayFor(model => model.About)
    </div>
    <br/>
    <br/>


    <button><a href="~/Home/info?JobOwnerId=@Model.FirstJobOwner ">Reserve</a></button>


    @*@Html.ActionLink("Reserve A Time", "Home", "info", new { JobOwnerId = Model.FirstJobOwner })*@
    @*<button name="reserve" id="reserve"><a href="~/Home/info/"></a></button>*@
    @*a button for reservation*@


    <br/>

</fieldset>

MyAppointer/Views/Job/Edit.cshtml
@model MyAppointer.Models.Jobs

@{
    ViewBag.Title = "Edit";
}

<h2>Edit</h2>

@using (Html.BeginForm()) {
    @Html.AntiForgeryToken()
    @Html.ValidationSummary(true)

    <fieldset>
        <legend>Jobs</legend>

        @Html.HiddenFor(model => model.Id)

        <div class="editor-label">
            @Html.LabelFor(model => model.Title)
        </div>
        <div class="editor-field">
            @Html.EditorFor(model => model.Title)
            @Html.ValidationMessageFor(model => model.Title)
        </div>

        <div class="editor-label">
            @Html.LabelFor(model => model.JobPhone)
        </div>
        <div class="editor-field">
            @Html.EditorFor(model => model.JobPhone)
            @Html.ValidationMessageFor(model => model.JobPhone)
        </div>

        <div class="editor-label">
            @Html.LabelFor(model => model.About)
        </div>
        <div class="editor-field">
            @Html.EditorFor(model => model.About)
            @Html.ValidationMessageFor(model => model.About)
        </div>

        <div class="editor-label">
            @Html.LabelFor(model => model.Address)
        </div>
        <div class="editor-field">
            @Html.EditorFor(model => model.Address)
            @Html.ValidationMessageFor(model => model.Address)
        </div>

        <div class="editor-label">
            @Html.LabelFor(model => model.JobTypeId, "JobTypes")
        </div>
        <div class="editor-field">
            @Html.DropDownList("JobTypeId", String.Empty)
            @Html.ValidationMessageFor(model => model.JobTypeId)
        </div>

        <div class="editor-label">
            @Html.LabelFor(model => model.FirstJobOwner, "Users")
        </div>
        <div class="editor-field">
            @Html.DropDownList("FirstJobOwner", String.Empty)
            @Html.ValidationMessageFor(model => model.FirstJobOwner)
        </div>

        <p>
            <input type="submit" value="Save" />
        </p>
    </fieldset>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

MyAppointer/Views/Job/Index.cshtml
@model IEnumerable<MyAppointer.Models.Jobs>

@{
    ViewBag.Title = "List of Jobs";
}


<br/>
@*<p>
    @Html.ActionLink("Create New", "Create")
</p>*@
<table font-size:1.35em;" >
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.Id)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Title)
        </th>
        <th>
            @Html.DisplayName("Name")
        </th>

        <th>
            @Html.DisplayNameFor(model => model.Users.City)
        </th>

        <th>
            @Html.DisplayNameFor(model => model.JobTypes.Title)
        </th>
        <th>
            @Html.DisplayName("Phone Number")
        </th>


        <th></th>
    </tr>

@foreach (var item in Model) {
    <tr>
        <td>
            @Html.DisplayFor(modelItem => item.Id)
        </td>
        <td>

            <a href="@Url.Action("Details", new { id=item.Id})">@Html.DisplayFor(modelItem => item.Title)</a>

            @*@Str=modelItem => item.Title;
            @Html.ActionLink(Convert.ToString(modelItem => item.Title), "Details", new { id = item.Id })*@
            
            @*@Html.DisplayFor(modelItem => item.Title)*@
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Users.FullName)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Users.City)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.JobTypes.Title)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.JobPhone)
        </td>
        
        </tr>
}

</table>